version: '3.8'

services:
  db:
    build: ./Backend/Docker/MysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bluechat_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    networks:
      - app-network

  api:
    build: ./Backend/Docker/Api
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user_password
      - DATABASE_NAME=bluechat_db
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./Backend/Docker/Site/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
